version: '3.7'

x-php: &common-php-container
  image: xhrequest/symfony_common:version-2.1.0
  working_dir: /var/www/app
  volumes:
    - .:/var/www/app:cached

services:
  test_platform:
    <<: *common-php-container
    command: ["php", "-v"]
